// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadProviderRuntimeRefreshFailure } from "./ThreadProviderRuntimeRefreshFailure";

export type ThreadProviderRuntimeRefreshAllLoadedResponse = { totalThreads: number, appliedThreadIds: Array<string>, queuedThreadIds: Array<string>, failedThreads: Array<ThreadProviderRuntimeRefreshFailure>, };
